name: Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Verify static files
        run: |
          echo "Content of widget-react-app/dist:"
          ls -la widget-react-app/dist/
          echo "Content of index.html:"
          cat widget-react-app/dist/index.html

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "j1tfyi-portal"
          entrypoint: "main.ts"
          include: |
            main.ts
            widget-react-app/dist/**/*