name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Clone Repository
      - name: Clone repository
        uses: actions/checkout@v3

      # Step 2: Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Create Sensitive Files
      - name: Create sensitive files
        run: |
          echo "${{ secrets.MAIN_TS_BASE64 }}" | base64 -d > main.ts
          echo "${{ secrets.BRIDGE_JSX_BASE64 }}" | base64 -d > bridge-react-app/src/useBridge.jsx
          echo "${{ secrets.APP_JSX_BASE64 }}" | base64 -d > bridge-react-app/src/App.jsx
          echo "${{ secrets.SERVICE_WORKER_BASE64 }}" | base64 -d > service-worker.js
          echo "${{ secrets.MANIFEST_BASE64 }}" | base64 -d > site.webmanifest

      # Step 4: Decode and Verify Files
      - name: Verify Files Exist
        run: |
          echo "Verifying files exist:"
          ls -l main.ts service-worker.js site.webmanifest

      # Step 5: Build React App
      - name: Build React app
        working-directory: bridge-react-app
        run: |
          npm install
          npm run build

      # Step 6: Verify Build Output
      - name: Verify Build Output
        run: |
          echo "Build output:"
          ls -R bridge-react-app/dist

      # Step 7: Upload to Deno Deploy
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "j1tfyi-ccp"
          entrypoint: "./main.ts"
          include: |
            main.ts
            deno.json
            deps.client.ts
            deps.server.ts
            bridge-react-app/dist/**/*
            service-worker.js
            site.webmanifest
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

      # Step 8: Cleanup
      - name: Cleanup
        if: always()
        run: |
          rm -f main.ts
          rm -f bridge-react-app/src/useBridge.jsx
          rm -f bridge-react-app/src/App.jsx
          rm -f service-worker.js
          rm -f site.webmanifest