name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create sensitive files
        run: |
          echo "${{ secrets.MAIN_TS_BASE64 }}" | base64 -d > main.ts
          echo "${{ secrets.BRIDGE_JSX_BASE64 }}" | base64 -d > bridge-react-app/src/useBridge.jsx

      - name: Build React app
        working-directory: bridge-react-app
        run: |
          npm install
          npm run build

      - name: Verify files
        run: |
          ls -la
          echo "Checking main.ts:"
          head -n 5 main.ts
          echo "Checking useBridge.jsx:"
          head -n 5 bridge-react-app/src/useBridge.jsx

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "j1tfyi-portal-app"
          entrypoint: "./main.ts"
          include: |
            main.ts
            deno.json
            deps.client.ts
            deps.server.ts
            bridge-react-app/dist/**/*
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

      - name: Cleanup
        if: always()
        run: |
          rm -f main.ts
          rm -f bridge-react-app/src/useBridge.jsx