name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create sensitive files
        run: |
          echo "${{ secrets.MAIN_TS_BASE64 }}" | base64 -d > main.ts
          echo "${{ secrets.BRIDGE_JSX_BASE64 }}" | base64 -d > bridge-react-app/src/useBridge.jsx
          echo "${{ secrets.APP_JSX_BASE64 }}" | base64 -d > bridge-react-app/src/App.jsx

      - name: Decode and Verify App.jsx Base64
        run: |
          echo "${{ secrets.APP_JSX_BASE64 }}" | base64 -d > decoded_app.jsx
          echo "Decoded App.jsx content:"
          cat decoded_app.jsx
          echo "Decoded file details:"
          file decoded_app.jsx
          echo "File size:"
          wc -c decoded_app.jsx
      
      - name: Verify App.jsx content
        run: cat bridge-react-app/src/App.jsx

      - name: Debug App.jsx
        run: |
          echo "Content of App.jsx:"
          cat bridge-react-app/src/App.jsx || echo "File not found"
          echo "Directory contents:"
          ls -R bridge-react-app/src
          echo "APP_JSX_BASE64 secret length:"
          echo "${{ secrets.APP_JSX_BASE64 }}" | wc -c

      - name: Build React app
        working-directory: bridge-react-app
        run: |
          npm install
          echo "Content of App.jsx before build:"
          cat src/App.jsx || echo "File not found"
          npm run build

      - name: Verify files
        run: |
          ls -la
          echo "Checking main.ts:"
          head -n 5 main.ts
          echo "Checking useBridge.jsx:"
          head -n 5 bridge-react-app/src/useBridge.jsx
          echo "Checking App.jsx:"
          cat bridge-react-app/src/App.jsx

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "j1tfyi-portal-app"
          entrypoint: "./main.ts"
          include: |
            main.ts
            deno.json
            deps.client.ts
            deps.server.ts
            bridge-react-app/dist/**/*
        env:
          DENO_DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}

      - name: Cleanup
        if: always()
        run: |
          rm -f main.ts
          rm -f bridge-react-app/src/useBridge.jsx
          rm -f bridge-react-app/src/App.jsx
